name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller rotatescreen pystray pillow flask screeninfo

      - name: Compilar o executável com PyInstaller
        run: |
          pyinstaller --onefile --windowed --add-data "templates;templates" --hidden-import "screeninfo" --hidden-import "rotatescreen" --add-data "icon.ico;." --icon "icon.ico" --name "Auto_Rotate_Oluas" main.py

      - name: Verificar arquivos gerados
        run: dir dist

      - name: Publicar artefato (executável)
        uses: actions/upload-artifact@v4
        with:
          name: auto-rotate-app
          path: dist/Auto_Rotate_Oluas.exe

  release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Baixar artefato
        uses: actions/download-artifact@v4
        with:
          name: auto-rotate-app
          path: .

      - name: Criar release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload do executável para a release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Auto_Rotate_Oluas.exe
          asset_name: Auto_Rotate_Oluas.exe
          asset_content_type: application/octet-stream
